name: eternalmodmanager
base: core20
version: '2.0.5'
summary: Mod manager for DOOM Eternal.
description: A cross platform mod manager for DOOM Eternal, making it easier to set-up and install mods in both Windows and Linux.
grade: stable
confinement: strict

parts:
  eternalmodmanager:
    plugin: dump
    source: EternalModManager/bin/Release/net6.0/linux-x64/publish
    stage-packages:
      - liblttng-ust0
      - x11-utils

plugs:
  steam-files:
    interface: personal-files
    write:
      - $HOME/.var/app/com.valvesoftware.Steam/steamapps/common/DOOMEternal
      - $HOME/.local/share/Steam/steamapps/common/DOOMEternal
      - $HOME/.steam/steam/steamapps/common/DOOMEternal

apps:
  eternalmodmanager:
    command: EternalModManager
    extensions: [gnome-3-38]
    plugs:
      - x11
      - desktop
      - network
      - removable-media
      - steam-files
    environment:
      DISABLE_WAYLAND: 1
