name: eternalmodmanager
base: core22
version: '3.0.1'
summary: Mod manager for DOOM Eternal.
description: A cross platform mod manager for DOOM Eternal, making it easier to set-up and install mods in both Windows and Linux.
grade: stable
confinement: strict

parts:
  eternalmodmanager:
    plugin: dump
    source: EternalModManager/bin/Release/net7.0/linux-x64/publish
    stage-packages:
      - x11-utils
      - curl
      - stterm

apps:
  eternalmodmanager:
    command: EternalModManager
    extensions: [gnome]
    plugs:
      - x11
      - desktop
      - network
    environment:
      DISABLE_WAYLAND: 1
